### ISSUE TITLE
Error metahandlers.py, line 1086

### ISSUE THREAD

**Issue by halidri** [Eldorados/script.module.metahandler#1]
Hi Eldorados,
I'va this error from the headline and this:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position12: ordinal not in range(128).
In log is only this:
Error connecting to TMDB: HTTP Error 401: Unauthorized, ok what i seen, we are banned from TMDB, right?

This error is on many series when i search metainfo. So also Marvel's Daredevil in xstreams burningseries addon.
Would be nice when you can fix this problem.

Thanks for your good work

**Comment by Eldorados** [comment]
They have shut down the api key that meta handlers was usingNow all addons need to get their own api key and pass it into meta handlers for it to work                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: halidriSent: Thursday, March 31, 2016 3:45 AMTo: Eldorados/script.module.metahandlerReply To: Eldorados/script.module.metahandlerSubject: [Eldorados/script.module.metahandler] Error metahandlers.py, line 1086 (#1)UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position12: ordinal not in range(128).
In log is only this:
Error connecting to TMDB: HTTP Error 401: Unauthorized, ok what i seen, we are banned from TMDB, right?

This error is on many series when i search metainfo. So also Marvel's Daredevil.
Would be nice when you can fix this problem.

Thanks

—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by halidri** [comment]
So you get your own api key or does it never work again?

**Comment by Eldorados** [comment]
?? I don't know what you are asking

Metahandlers no long supplies an api key, for any addon using it the addon
developer must get their own TMDB api key and pass it in

**Comment by halidri** [comment]
Ok, checked! :)
thanks
